Library/Entity/baseEntity.php
<?php

namespace Eckinox\Library\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Eckinox\Library\Symfony\Doctrine\LocaleFilter;

trait baseEntity {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;

    /*
     * Getters & setters
     */

    public function setId($id){
		$this->id = $id;
	}

    public function getId() {
        return $this->id;
    }

    public function setCreatedAt($datetime = null) {
        $this->createdAt = $this->_datetime($datetime);
    }

    public function getCreatedAt() {
        return $this->createdAt;
    }

    public function setUpdatedAt($datetime = null) {
        $this->updatedAt = $this->_datetime($datetime);
    }

    public function getUpdatedAt() {
        return $this->updatedAt;
    }

    public function assign($data) {
        foreach($data as $key => $value) {
            $this->$key = $value;
        }

        return $this;
    }

    public function set($property, $value) {
        $methodName = 'set' . ucfirst($property);

        if (method_exists($this, $methodName)) {
            $this->$methodName($value);
        } else if (property_exists($this, $property)) {
            $this->$property = $value;
        } else {
            throw new \Exception("There is no corresponding property or method for \"" . $property . "\" in " . static::class);
        }

        return $this;
    }

    public function get($property) {
        $methodName = 'get' . ucfirst($property);

        if (method_exists($this, $methodName)) {
            return $this->$methodName();
        } else if (property_exists($this, $property)) {
            try {
                return $this->$property;
            } catch(\Exception $e) {
                return $this::$$property;
            }
        } else {
            throw new \Exception("There is no corresponding property or method for \"" . $property . "\" in " . static::class);
        }

        return null;
    }

    public function getRecursively($property) {
        if (!$property) {
            return null;
        }

        $parts = explode('.', $property);
        $key = array_shift($parts);

        $value = $this->get($key);

        while (count($parts)) {
            if (method_exists($value, 'getRecursively')) {
                return $value->getRecursively(implode('.', $parts));
            } else {
                $key = array_shift($parts);

                if (is_array($value) && array_key_exists($key, $value)) {
                    $value = $value[$key];
                } else if ($value instanceof \ArrayAccess && $value->offsetExists($key)) {
                    $value = $value[$key];
                } else if (is_object($value) && property_exists($value, $key)) {
                    $value = $value->$key;
                } else {
                    return null;
                }
            }
        }

        return $value;
    }

    public function getRawObject($returnEntityId = false, $dateFormat = null, $includeRelations = false) {
        $data = [];

        foreach (static::getClassProperties() as $property) {
            if ($property == 'translations') {
                continue;
            }

            $value = $this->get($property);

            if ($value instanceof Collection) {
                $relationData = [];
                foreach ($value as $entity) {
                    # @TODO: Inlcude sub-relations by managing recursion correctly
                    if (method_exists($entity, 'getRawObject')) {
                        $relationData[] = $entity->getRawObject($returnEntityId, $dateFormat, false);
                    }
                }
                $value = $relationData;
            } else if (is_object($value)) {
                if(method_exists($value, 'getId')) {
                    if ($returnEntityId) {
                        $value = $value->getId();
                    } else if (method_exists($value, 'getRawObject')) {
                        $value = $value->getRawObject(true, $dateFormat, false);
                    }
                } else if($dateFormat && method_exists($value, 'format')) {
                    $value = $value->format($dateFormat);
                }
            }

            $data[$property] = $value;
        }

        return $data;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeDatetimes()
    {
        if (!$this->createdAt) {
            $this->createdAt = $this->_datetime();
        }

        $this->updatedAt = $this->_datetime();
    }

    protected function _datetime($datetime = null) {
        return $datetime ? ( is_string($datetime) ? new \DateTime($datetime) : $datetime ) : new \DateTime('now') ;
    }

    static public function getClassProperties() {
		return array_keys(get_class_vars(get_called_class()));
	}

    static public function getClassMethods() {
		return get_class_methods(get_called_class());
	}

    static public function getClassName() {
        return get_called_class();
    }

    static public function getTransKey() {
        $class = get_called_class();
        $key = substr($class, strrpos($class, '\\') + 1);
        return lcfirst($key);
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function verifyTranslatableRelations(LifecycleEventArgs $args = null) {
        $em = $args->getEntityManager();
        $metadata = $em->getClassMetadata(get_class($this));
        $db = $em->getConnection();

        $traits = class_uses(static::class);
        $translatabletraitName = 'Eckinox\\Library\\Entity\\translatableEntity';
        $properties = array_keys(get_object_vars($this));

        # If this is a translatable entity, the relations are kept as is.
        if (in_array($translatabletraitName, $traits)) {
            return;
        }

        # Find each relation to translatable entities, and add all translations of the selected entities to the collection
        foreach ($properties as $property) {
            # Skip properties that aren't collections
            if (!($this->$property instanceof Collection) || !count($this->$property)) {
                continue;
            }

            $relationTraits = class_uses($this->$property->first());

            # Skip relations that aren't translatable
            if (!in_array($translatabletraitName, $relationTraits)) {
                continue;
            }

            # Fetch every translation of the entities contained in this relation
            $newTranslations = [];
            $deletedRelations = [];
            foreach ($this->$property as $entity) {
                if ($args instanceof PreUpdateEventArgs) {
                    if (method_exists($this->$property, 'getDeleteDiff') && $this->$property->getDeleteDiff()) {
                        $deletedRelations = $this->$property->getDeleteDiff();
                    }
                }

                if (method_exists($this->$property, 'getInsertDiff') && in_array($entity, $this->$property->getInsertDiff())) {
                    foreach ($entity->getTranslations() as $translation) {
                        $newTranslations[] = $translation;
                    }
                }
            }

            # Add every new translation to the relation
            foreach ($newTranslations as $translation) {
                if (!$this->$property->contains($translation)) {
                    $this->$property->add($translation);
                }
            }

            # Remove translation from the relation as well
            # This bit probably requires some explanation, so please read this before atetmpting to change anything inside this IF statement.
            # We can't simply do a $this->$property->remove($translation) to remove translations, because the locale SQL filter restricts Doctrine from loading said translations
            # We cannot simply disable the SQL filter to load the translations, as Doctrine has already cached the results of those queries with the filter turned on.
            # We cannot detach or refresh entity from the EntityManager, because we are in the middle of processing the flush(), and Doctrine very much dislikes us doing that.
            # Therefore, the solution that has been found as a counter to these issues, in order to remove all translations of a relation when removing said translation, is as follows.
            # We fetch the metadata of the relation and of that relation's translations property in order to manually build an SQL query that will remove relations to those relations' translations
            if ($deletedRelations) {
                # Get the association data between the current entity class and the relation entity class
                $associationMapping = $metadata->getAssociationMapping($property);
                $associationTable = $associationMapping['joinTable']['name'];
                $associationSourceColumn = $associationMapping['joinTable']['joinColumns'][0]['name'];
                $associationTargetColumn = $associationMapping['joinTable']['inverseJoinColumns'][0]['name'];

                # Get the target entity class translation metadata
                $targetMetadata = $em->getClassMetadata($associationMapping['targetEntity']);

Controller/Application/DefaultController.php
<?php

namespace Eckinox\Controller\Application;

use Eckinox\Library\Symfony\Controller,
    Eckinox\Library\Symfony\Annotation\Breadcrumb,
    Eckinox\Library\Symfony\Annotation\Lang;

use Symfony\Component\HttpFoundation\Request,
    Symfony\Component\Routing\Annotation\Route;

use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;

/**
 *  @Lang(domain="application", default_key="dashboard")
 */
class DefaultController extends Controller
{
    /**
     * @Route("/", name="home")
     * @Breadcrumb(parent=false)
     */
    public function home(Request $request)
    {
        $user = $this->getUser();

        return $this->render('@Eckinox/application/home.html.twig', array(
            'user' => $this->getUser(),
        ));
    }

}

Controller/Application/JsEntityController.php
<?php

namespace Eckinox\Controller\Application;

use Eckinox\Library\Symfony\Controller;
use Eckinox\Library\Symfony\Annotation\JsEntityProperty;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\JsonResponse;

class JsEntityController extends Controller
{
    /**
     * @Route("/json/entity", name="json_entity")
     */
    public function getEntityJson(Request $request, $entityName)
    {
        // TODO: load only one entity by id

        $json = [];
        $className = strtr('App\Entity\%entity%', [ '%entity%' => $entityName ]);

        list($properties, $relations) = $this->getRequestParameters($className);

        $rows = $this->getDoctrine()
            ->getRepository($className)
            ->findAllRows($properties, $relations);

        return new JsonResponse($rows);
    }

    private function getRequestParameters($className) {
        $reader = new AnnotationReader();
        $reflectionClass = new \ReflectionClass($className);

        $properties = [];
        $relations = [];

        foreach($reflectionClass->getProperties() as $property){
            $annotation = $reader->getPropertyAnnotation($property, JsEntityProperty::class);

            if($annotation) {
                $isEntity = property_exists($reader->getPropertyAnnotation($property, ORM\Annotation::class), 'targetEntity');
                $protertyName = $annotation->getName() ?: $property->name;

                $properties[] = $protertyName;

                if($isEntity) {
                    $relations[] = $protertyName;
                }
            }
        }

        return [ $properties, $relations ];
    }
}

Controller/Application/LogController.php
<?php

namespace Eckinox\Controller\Application;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Eckinox\Entity\Application\Log;
use Eckinox\Library\General\Arrays;

class LogController extends AbstractController
{
    use \Eckinox\Library\Application\log;
    use \Eckinox\Library\General\appData;

    /**
     * @Route("/log/{page}", name="index_log", requirements={"page"="\d+"})
     */
    public function index(Request $request, $page = 1)
    {
        $log_repository = $this->getDoctrine()->getRepository(Log::class);
        $maxResults = $this->data('application.log.config.list.items_shown');

        $logs = $log_repository->getList($page, $maxResults);
        $count = $log_repository->getCount();
        $nbPages = intval(ceil($count / $maxResults));

        return $this->render('@Eckinox/application/log/index.html.twig', array(
            'logs' => $logs,
            'currentPage' => $page,
            'count' => $count,
            'nbPages' => $nbPages,
        ));
    }

    /**
     * @Route("/log/view/{log_id}", name="view_log", requirements={"log_id"="\d+"})
     */
    public function view(Request $request, $log_id = null)
    {
        $log = $this->getDoctrine()
            ->getRepository(Log::class)
            ->find($log_id);

        return $this->render('@Eckinox/application/log/view.html.twig', array(
            'log' => $log,
        ));
    }
}

Controller/Application/SoftwareController.php
<?php

namespace Eckinox\Controller\Application;

use Eckinox\Library\Symfony\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Eckinox\Library\General\Arrays;
use Eckinox\Library\General\Serializer;
use Eckinox\Library\General\Git;
use Eckinox\Library\Symfony\Annotation\Security;
use Eckinox\Library\Symfony\Annotation\Lang;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 *  @Lang(domain="application", default_key="software")
 */
class SoftwareController extends Controller
{
    use \Eckinox\Library\Application\log;
    use \Eckinox\Library\General\appData;

    protected $securityRedirect = 'home';

    /**
     * @Route("/software/update", name="index_software")
     * @Security(privilege="SOFTWARE_UPDATE")
     */
    public function update(Request $request) {
        $filechanged = Git::getFileChanged();
        $version = Git::getCommitDate('Y-m-d H:i:s');

        if ($action = $request->request->get('action')) {
            switch($action) {
                case "update":
                    if ( ! $filechanged ) {
                        $shell = Git::pull("Eckidev/origin");
                    }

                    break;
            }
        }

        if ( $filechanged ) {
            $shell = "-- Files changed --\n$filechanged";
        }

        return $this->render('@Eckinox/application/software/update.html.twig', [
            'shell' => $shell ?? "",
            'version' => $version,
            'updatable' => empty($filechanged),
            'update_available' => Git::getUpdateCount("Eckidev/origin"),
            'title' => $this->lang('title.'.$request->get('_route')),
        ]);
    }
}

Resources/views/application/import/index.html.twig
{% extends '@Eckinox/base.html.twig' %}
{% trans_default_domain 'application' %}

{% set previewResultsFirst = settings.preview is defined and settings.preview %}

{% block header %}
    <h2>{{ ('privileges.labels.import.IMPORT_' ~ (importType | camelToSnakeCase | upper )) | trans }}</h2>
{% endblock %}

{% block content %}

    <form name="import" method="post" ajax-action="{{ path('ajax_get_json_from_excel') }}" ajax-type="json" id="upload-form">
        <div class="block-wrapper">
            <div class="block block-full file-selector">
                <div class="fields">
                    <div class="field-wrapper import-file half">
                        <label for="import-file">{% trans %}import.fields.file{% endtrans %}</label>
                        <input type="file" id="import-file" name="file" class="import-file" accept=".xlsx,.xls,.xlsm,.csv" required />
                    </div>

                    <div class="field-wrapper submit">
                        <button class="button" type="submit">{% trans %}import.fields.load_file{% endtrans %} &nbsp;<i class="fa fa-upload" aria-hidden="true"></i></button>
                    </div>
                </div>
            </div>

            <div class="block block-full change-file hide">
                <div class="fields">
                    <div class="field-wrapper half">
                        <button class="button red import-reset" type="button">{% trans %}import.fields.change_file{% endtrans %} &nbsp;<i class="fa fa-undo" aria-hidden="true"></i></button>
                    </div>
                    <div class="field-wrapper half text-right">
                        <button type="submit" form="import-form" class="button import">{% trans %}import.fields.import{% endtrans %} &nbsp;<i class="fa fa-file-import" aria-hidden="true"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="block-wrapper import-processing hide">
        <div class="block block-full">
            <form class="import-preview hide" id="import-form" method="POST" {{ previewResultsFirst ? 'ajax-action' : 'action' }}="{{ path(previewResultsFirst ? 'preview_import' : 'process_import', { importType: importType }) }}">
                <input type="hidden" name="data">

                <div class="fields">
                    <div class="field-wrapper half select-sheet">
                        <label for="worksheet">{% trans %}import.fields.worksheet{% endtrans %}</label>
                        <select id="worksheet" name="worksheet" class="worksheet"></select>
                    </div>
                    <div class="field-wrapper half starting-line">
                        <label for="starting-line">{% trans %}import.fields.startingLine{% endtrans %}</label>
                        <input type="number" id="starting-line" name="starting_line" class="starting-line" value="1" min="1" max="1">
                    </div>
                </div>
                <div class="fields custom-fields">
                    {% for name, field in (settings.customFields is defined ? settings.customFields : []) %}
                        <div class="field-wrapper half {{ name }}">
                            <label for="">{{ field.label | trans }}</label>
                            {{ custom_field(name, field) }}
                        </div>
                    {% endfor %}
                </div>
                <div class="fields assignations">
                    <select class="assignation-select-template hide">
                        <option value="">{% trans %}import.excel.assignations.select{% endtrans %}</option>

                        {# Outputting the basic properties the entity #}
                        <optgroup label="{{ (entity.transKey ~ '.title') | trans }}">
                            {% for property in entity.getClassProperties() %}
                                {% if (settings.properties[property].disabled is not defined or not settings.properties[property].disabled) and
                                      (settings.properties[property].relation is not defined or not settings.properties[property].relation) and
                                      settings.properties[property].value is not defined and
                                      property not in ["createdAt", "updatedAt", "isArchived", "_temporaryData"] %}
                                    <option value="{{ property }}" data-key="{{ property }}">{{ ((settings.transKey is defined ? settings.transKey : entity.transKey) ~ '.fields.' ~ property) | trans }}</option>
                                {% endif %}
                            {% endfor %}
                        </optgroup>

                        {# Outputting the relation groups with their properties #}
                        {% for property, propertyInfos in (settings.properties is defined ? settings.properties : []) %}
                            {% if (propertyInfos.disabled is not defined or not propertyInfos.disabled) and
                                  (propertyInfos.relation is defined and propertyInfos.relation) and
                                  (propertyInfos.allowedProperties is defined and propertyInfos.allowedProperties | length) %}
                                {% set transKey = propertyInfos.relation | split('\\') | last | lcfirst %}
                                {% set repeatable = propertyInfos.repeatable is defined ? propertyInfos.repeatable : false %}
                                <optgroup label="{{ (propertyInfos.title is defined ? propertyInfos.title : (transKey ~ '.title')) | trans }}{{ repeatable ? ' (1)' : '' }}" original-label="{{ (propertyInfos.title is defined ? propertyInfos.title : (transKey ~ '.title')) | trans }}" class="relation-group" property="{{ property }}" data-index="0">
                                    {% for relationProperty in propertyInfos.allowedProperties %}
                                        {% set relationPropertyKey = property ~ '.' ~ (repeatable ? '0.' : '') ~ relationProperty %}
                                        <option value="{{ relationPropertyKey }}" data-key="{{ property ~ '.' ~ relationProperty }}">{{ (transKey ~ '.fields.' ~ relationProperty) | trans }}</option>
                                    {% endfor %}
                                </optgroup>
                            {% endif %}
                        {% endfor %}

                        {% if settings.allowArchive is defined and settings.allowArchive %}
                            <optgroup label="{% trans %}import.fields.managementOptgroup{% endtrans %}">
                                <option value="_archive_" data-key="_archive_">{% trans %}import.fields.archiveOption{% endtrans %}</option>
                            </optgroup>
                        {% endif %}
                    </select>
                    <div class="field-wrapper">
                        <label>{% trans %}import.fields.assignations{% endtrans %}</label>
                        <div class="columns"></div>
                    </div>
                </div>
                <div class="fields">
                    <div class="field-wrapper full preview-wrapper">
                        <table class="excel-preview partial"></table>
                    </div>

                    <div class="field-wrapper button-container">
                        <button type="submit" class="button import">{% trans %}import.fields.import{% endtrans %} &nbsp;<i class="fa fa-file-import" aria-hidden="true"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/modules/import.js', 'eckinox') }}"></script>
    <script>
        window.addEventListener('load', function(){
            let flow = ImportFlow.init({{ settings | json_encode() | raw }}, {{ autoload_data | json_encode | raw }});
        });

        let importForm = document.querySelector('#import-form');
        let modalButtonsHtml = `
            <button class="button cancel grey" action="remove">{% trans %}cancel{% endtrans %}</button>
            <button class="button submit">{% trans %}import.preview.submit{% endtrans %}</button>
        `;

        importForm.addEventListener('ajax-response', function(e) {
            BundleUI.showModal("{% trans %}import.preview.modalTitle{% endtrans %}", e.detail, modalButtonsHtml, 'import-results-preview-modal');
        });

        Dom.delegate('click', '.import-results-preview-modal .submit', function(e){
            e.preventDefault();

            importForm.removeAttribute('ajax-action');
            importForm.setAttribute('action', '{{ path('process_import', { importType: importType }) }}');
            importForm.submit();

            for (let button of (this.closest('.import-results-preview-modal').querySelectorAll('button'))) {
                button.disabled = true;
            }

            this.classList.add('loading');
        });
    </script>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/modules/import.css', 'eckinox') }}" />
{% endblock %}

Resources/views/application/import/results_preview.html.twig
{% trans_default_domain 'application' %}

{% if response.success %}
    {% set resultsCount = 0 %}

    <div class="import-results-preview success">
        <div class="title">{% trans %}import.preview.success{% endtrans %}</div>
        <div class="content">
            {% for changeType, entityChanges in response.data if entityChanges | length %}
                <div class="changes-wrapper">
                    <div class="subtitle">{{ ('import.preview.' ~ changeType) | trans }}</div>
                    {% for entityClass, count in entityChanges if entityClass not in (settings.previewIgnore is defined ? settings.previewIgnore : []) %}
                        <div class="change-entry {{ changeType }}">
                            <span class="count">{{ count }}</span> {{ ((entityClass | lcfirst) ~ '.title') | trans | lcfirst }}
                        </div>

                        {% set resultsCount = resultsCount + 1 %}
                    {% endfor %}
                </div>
            {% endfor %}

            {% if resultsCount == 0 %}
                {% trans %}import.preview.noChanges{% endtrans %}
            {% endif %}
        </div>
    </div>
{% else %}
    <div class="import-results-preview error">
        <div class="title">{% trans %}import.preview.error{% endtrans %}</div>
        <div class="content">{{ response.error }}</div>
    </div>
{% endif %}